# Generated by Django 4.2.3 on 2023-12-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_year', models.CharField(max_length=255)),
                ('attend_brown_or_risd', models.CharField(max_length=255)),
                ('board_membership', models.CharField(max_length=255)),
                ('is_executive_board_member', models.BooleanField(default=False)),
                ('is_new_staffer_this_semester', models.BooleanField(default=False)),
                ('ethnicity', models.CharField(max_length=255)),
                ('is_fgli', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=255)),
                ('sexual_orientation', models.CharField(max_length=255)),
                ('is_international', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
