# Generated by Django 4.2.3 on 2023-12-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='is_executive_board_member',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='is_fgli',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='is_international',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='is_new_staffer_this_semester',
            field=models.CharField(max_length=255),
        ),
    ]
